exports.specialists = [
  'Allergist',
  'Andrologist',
  'Anesthesiologist',
  'Audiologist',
  'Cardiologist',
  'Cardiothoracic Surgeon',
  'Dentist',
  'Dermatologist',
  'Endocrinologist',
  'ENT Doctor (Otolaryngologist)',
  'Family Doctor (General Practitioner)',
  'Gastroenterologist',
  'General Surgeon',
  'Gynecologist',
  'Hematologist',
  'Hepatologist',
  'Infertility Specialist',
  'Internist',
  'Laboratory',
  'Nephrologist',
  'Neurologist',
  'Neurosurgeon',
  'Nutritionist',
  'Obesity Surgeon',
  'Oncologist',
  'Ophthalmologist',
  'Orthopedist',
  'Pediatric Surgeon',
  'Pediatrician',
  'Phoniatrician',
  'Physiotherapist',
  'Plastic Surgeon',
  'Psychiatrist',
  'Pulmonologist',
  'Radiologist',
  'Rheumatologist',
  'Urologist',
  'Vascular Surgeon',
];
