import "@/styles/globals.css";
import { Inter } from "next/font/google";
import Providers from "@/Components/Providers";
import Header from "@/Components/app/Header";
import Footer from "@/Components/app/Footer";
import ProgessBar from "@Components/Layouts/ProgessBar";
export const metadata = {
  title: "Helth care",
  description: "Generated by create next app",
};
const inter = Inter({ subsets: ["latin"] });
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`bg-white text-slate-900 antialiased ${inter.className}`}
    >
      <head>
        <link rel="stylesheet" type="text/css" href="/nprogress.css" />
      </head>
      <body>
        <Providers>
          <ProgessBar />
          <Header />
          {children}
          <Footer />
        </Providers>
        {/* <div className="h-40 md:hidden"></div> */}
      </body>
    </html>
  );
}
