import "@styles/globals.css";
import { Inter } from "next/font/google";
import Providers from "@app/Providers";
import Chat from "@Components/GPT3.5/Chat";
// import ProgessBar from "@Components/Layouts/ProgessBar";

export const metadata = {
  title: "Helth care",
  description: "Generated by create next app",
};
const inter = Inter({ subsets: ["latin"] });
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`bg-whit text-slate-900 antialiased ${inter.className}`}
    >
      <body className="dark:bg-slate-900">
        <Providers>
          <Chat />
          {children}
        </Providers>
      </body>
    </html>
  );
}
